### ISSUE TITLE
Implémenter un script python qui permet de recheche un port de libre sur un serveur

### ISSUE THREAD

**Issue by stephane-klein** [harobed/personnal-notebook#330]
Je souhaite pouvoir déployer sur un serveur plusieurs services de ce type :

```
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 127.0.0.1:{{.Env.POSTGRES_PORT}}:5432
    volumes:
      - /var/lib/my_app/{{ .Env.BRANCH_NAME }}/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      start_period: 30s
```

Problème : je dois trouver à chaque fois un port de libre sur le serveur.

Pour cela, je souhaite réaliser un script du style :

```
$ seach_available_port.py --from=5433 --name=my_branch_name --state=assigned_ports.json
```

Une fois le port trouvé, le fichier `assigned_ports.json` doit contenir, par exemple :

```
{
  "my_branch_name": 5438
}
```

```
$ get_instance_port.py --state=assigned_ports.json --name=my_branch_name
5438
```

```
$ remove_instance_port.py  --state=assigned_ports.json --name=my_branch_name
```
